package com.warriorg.test.model;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 集装箱信息
 * 
 * generated by Generate 神码
 * @author builder
 * @date: 2019-10-15
 */
@Setter @Getter
@Table(name = "PREDECCONTAINERVO")
public class Predeccontainervo implements Serializable {
    private static final long serialVersionUID = 1L;

    
    /**
     * None
     */
    @Column(name = "ADDLIST")
    private String addlist;
    
    /**
     * 集装箱规格编码
     */
    @Column(name = "CNTNRMODECODE")
    private String cntnrmodecode;
    
    /**
     * 集装箱规格  
     */
    @Column(name = "CNTNRMODECODENAME")
    private String cntnrmodecodename;
    
    /**
     * 集装箱规格编码
     */
    @Column(name = "CONTAINERMDCODE")
    private String containermdcode;
    
    /**
     * 集装箱规格  
     */
    @Column(name = "CONTAINERMDCODENAME")
    private String containermdcodename;
    
    /**
     * 集装箱号
     */
    @Column(name = "CONTAINERNO")
    private String containerno;
    
    /**
     * 自重（KG）
     */
    @Column(name = "CONTAINERWT")
    private String containerwt;
    
    /**
     * 关联字段（统一编码）
     */
    @Column(name = "CONTSEQNO")
    private String contseqno;
    
    /**
     * 统一编码
     */
    @Column(name = "CUS_CIQ_NO")
    private String cusCiqNo;
    
    /**
     * 数据来源（0：固定 1：电子口岸 2：爬网 3：组合）
     */
    @Column(name = "DATA_SOURCE")
    private String dataSource;
    
    /**
     * 集装箱货重（过期）
     */
    @Column(name = "GOODSCONTAWT")
    private String goodscontawt;
    
    /**
     * 商品项号
     */
    @Column(name = "GOODSNO")
    private String goodsno;
    
    /**
     * None
     */
    @Column(name = "INSERT_TIME")
    private Date insertTime;
    
    /**
     * None
     */
    @Column(name = "INSERT_USER")
    private String insertUser;
    
    /**
     * 拼箱标识
     */
    @Column(name = "LCLFLAG")
    private String lclflag;
    
    /**
     * 拼箱标识中文
     */
    @Column(name = "LCLFLAGNAME")
    private String lclflagname;
    
    /**
     * 统一编码
     */
    @Column(name = "SEQ_NO")
    private String seqNo;
    
    /**
     * None
     */
    @Column(name = "SID")
    private String sid;
    
    /**
     * None
     */
    @Column(name = "UPDATE_TIME")
    private Date updateTime;
    
    /**
     * None
     */
    @Column(name = "UPDATE_USER")
    private String updateUser;
    
}