package com.warriorg.test.dto;

import lombok.Getter;
import lombok.Setter;
import io.swagger.annotations.ApiModelProperty;

/**
 * 集装箱信息
 * 
 * generated by Generate dc
 * @author builder
 * @date: 2019-10-15
 */
@ApiModel(value = "集装箱信息 DTO")
@Setter @Getter
public class PredeccontainervoDto implements Serializable {
    private static final long serialVersionUID = 1L;

    
    /**
     *
     */
    private String addlist;
    
    /**
     *集装箱规格编码
     */
    @ApiModelProperty(value = "集装箱规格编码")
    private String cntnrmodecode;
    
    /**
     *集装箱规格  
     */
    @ApiModelProperty(value = "集装箱规格  ")
    private String cntnrmodecodename;
    
    /**
     *集装箱规格编码
     */
    @ApiModelProperty(value = "集装箱规格编码")
    private String containermdcode;
    
    /**
     *集装箱规格  
     */
    @ApiModelProperty(value = "集装箱规格  ")
    private String containermdcodename;
    
    /**
     *集装箱号
     */
    @ApiModelProperty(value = "集装箱号")
    private String containerno;
    
    /**
     *自重（KG）
     */
    @ApiModelProperty(value = "自重（KG）")
    private String containerwt;
    
    /**
     *关联字段（统一编码）
     */
    @ApiModelProperty(value = "关联字段（统一编码）")
    private String contseqno;
    
    /**
     *统一编码
     */
    @ApiModelProperty(value = "统一编码")
    private String cusCiqNo;
    
    /**
     *数据来源（0：固定 1：电子口岸 2：爬网 3：组合）
     */
    @ApiModelProperty(value = "数据来源（0：固定 1：电子口岸 2：爬网 3：组合）")
    private String dataSource;
    
    /**
     *集装箱货重（过期）
     */
    @ApiModelProperty(value = "集装箱货重（过期）")
    private String goodscontawt;
    
    /**
     *商品项号
     */
    @ApiModelProperty(value = "商品项号")
    private String goodsno;
    
    /**
     *
     */
    private Date insertTime;
    
    /**
     *
     */
    private String insertUser;
    
    /**
     *拼箱标识
     */
    @ApiModelProperty(value = "拼箱标识")
    private String lclflag;
    
    /**
     *拼箱标识中文
     */
    @ApiModelProperty(value = "拼箱标识中文")
    private String lclflagname;
    
    /**
     *统一编码
     */
    @ApiModelProperty(value = "统一编码")
    private String seqNo;
    
    /**
     *
     */
    private String sid;
    
    /**
     *
     */
    private Date updateTime;
    
    /**
     *
     */
    private String updateUser;
    
}