package com.warriorg.test.dto;

import lombok.Getter;
import lombok.Setter;
import io.swagger.annotations.ApiModelProperty;

/**
 * 集装箱信息
 * 
 * generated by Generate 神码
 * @author builder
 * @date: 2019-10-15
 */
@ApiModel(value = "集装箱信息 新增修改参数")
@Setter @Getter
public class PredeccontainervoParam implements Serializable {
    private static final long serialVersionUID = 1L;

    
    /**
     *
     */
    @XdoSize(max = 200, message = "None长度不能超过200位字节长度(一个汉字2位字节长度)!") 
    private String addlist;
    
    /**
     *集装箱规格编码
     */
    @ApiModelProperty(value = "集装箱规格编码")
    @XdoSize(max = 200, message = "集装箱规格编码长度不能超过200位字节长度(一个汉字2位字节长度)!") 
    private String cntnrmodecode;
    
    /**
     *集装箱规格  
     */
    @ApiModelProperty(value = "集装箱规格  ")
    @XdoSize(max = 200, message = "集装箱规格  长度不能超过200位字节长度(一个汉字2位字节长度)!") 
    private String cntnrmodecodename;
    
    /**
     *集装箱规格编码
     */
    @ApiModelProperty(value = "集装箱规格编码")
    @XdoSize(max = 200, message = "集装箱规格编码长度不能超过200位字节长度(一个汉字2位字节长度)!") 
    private String containermdcode;
    
    /**
     *集装箱规格  
     */
    @ApiModelProperty(value = "集装箱规格  ")
    @XdoSize(max = 200, message = "集装箱规格  长度不能超过200位字节长度(一个汉字2位字节长度)!") 
    private String containermdcodename;
    
    /**
     *集装箱号
     */
    @ApiModelProperty(value = "集装箱号")
    @XdoSize(max = 200, message = "集装箱号长度不能超过200位字节长度(一个汉字2位字节长度)!") 
    private String containerno;
    
    /**
     *自重（KG）
     */
    @ApiModelProperty(value = "自重（KG）")
    @XdoSize(max = 200, message = "自重（KG）长度不能超过200位字节长度(一个汉字2位字节长度)!") 
    private String containerwt;
    
    /**
     *关联字段（统一编码）
     */
    @ApiModelProperty(value = "关联字段（统一编码）")
    @XdoSize(max = 200, message = "关联字段（统一编码）长度不能超过200位字节长度(一个汉字2位字节长度)!") 
    private String contseqno;
    
    /**
     *统一编码
     */
    @ApiModelProperty(value = "统一编码")
    @XdoSize(max = 18, message = "统一编码长度不能超过18位字节长度(一个汉字2位字节长度)!")
    @NotEmpty(value = "统一编码不能为空！") 
    private String cusCiqNo;
    
    /**
     *数据来源（0：固定 1：电子口岸 2：爬网 3：组合）
     */
    @ApiModelProperty(value = "数据来源（0：固定 1：电子口岸 2：爬网 3：组合）")
    @XdoSize(max = 1, message = "数据来源（0：固定 1：电子口岸 2：爬网 3：组合）长度不能超过1位字节长度(一个汉字2位字节长度)!")
    @NotEmpty(value = "数据来源（0：固定 1：电子口岸 2：爬网 3：组合）不能为空！") 
    private String dataSource;
    
    /**
     *集装箱货重（过期）
     */
    @ApiModelProperty(value = "集装箱货重（过期）")
    @XdoSize(max = 200, message = "集装箱货重（过期）长度不能超过200位字节长度(一个汉字2位字节长度)!") 
    private String goodscontawt;
    
    /**
     *商品项号
     */
    @ApiModelProperty(value = "商品项号")
    @XdoSize(max = 200, message = "商品项号长度不能超过200位字节长度(一个汉字2位字节长度)!") 
    private String goodsno;
    
    /**
     *
     */ 
    private Date insertTime;
    
    /**
     *
     */
    @XdoSize(max = 50, message = "None长度不能超过50位字节长度(一个汉字2位字节长度)!")
    @NotEmpty(value = "None不能为空！") 
    private String insertUser;
    
    /**
     *拼箱标识
     */
    @ApiModelProperty(value = "拼箱标识")
    @XdoSize(max = 200, message = "拼箱标识长度不能超过200位字节长度(一个汉字2位字节长度)!") 
    private String lclflag;
    
    /**
     *拼箱标识中文
     */
    @ApiModelProperty(value = "拼箱标识中文")
    @XdoSize(max = 200, message = "拼箱标识中文长度不能超过200位字节长度(一个汉字2位字节长度)!") 
    private String lclflagname;
    
    /**
     *统一编码
     */
    @ApiModelProperty(value = "统一编码")
    @XdoSize(max = 18, message = "统一编码长度不能超过18位字节长度(一个汉字2位字节长度)!")
    @NotEmpty(value = "统一编码不能为空！") 
    private String seqNo;
    
    /**
     *
     */
    @XdoSize(max = 36, message = "None长度不能超过36位字节长度(一个汉字2位字节长度)!")
    @NotEmpty(value = "None不能为空！") 
    private String sid;
    
    /**
     *
     */ 
    private Date updateTime;
    
    /**
     *
     */
    @XdoSize(max = 50, message = "None长度不能超过50位字节长度(一个汉字2位字节长度)!") 
    private String updateUser;
    
}